# Generated by Django 3.2.9 on 2021-11-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=12)),
                ('status', models.IntegerField(choices=[(1, 'Credit'), (2, 'Leasing')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='car.car')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='car.positioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('sum', models.FloatField(default=0)),
                ('percent', models.FloatField(default=12)),
                ('total', models.FloatField(default=0)),
                ('remain', models.FloatField(default=0)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.credit')),
            ],
        ),
    ]
