# Generated by Django 3.2.9 on 2021-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute_category',
            options={'verbose_name_plural': 'Attribute_Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='positioncategory',
            options={'verbose_name_plural': 'PositionCategories'},
        ),
        migrations.AlterField(
            model_name='position',
            name='engine_power',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='max_speed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='working_volume',
            field=models.PositiveIntegerField(),
        ),
    ]
