# Generated by Django 3.2.9 on 2021-11-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211104_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_ibi',
            field=models.PositiveIntegerField(),
        ),
    ]
