# Generated by Django 3.2.9 on 2021-11-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_attribute_category_car_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colored_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_ibi', models.PositiveIntegerField()),
                ('color_title', models.CharField(max_length=255)),
                ('color_code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='color-image/%Y/%m/%d')),
            ],
        ),
        migrations.RenameModel(
            old_name='Colored_Image',
            new_name='Image_for_Car_PositionCategory',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='colored_images',
            name='car_position_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.image_for_car_positioncategory'),
        ),
    ]
