# Generated by Django 3.2.9 on 2021-11-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20211104_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colored_Images',
            new_name='Colored_Image',
        ),
        migrations.AlterModelOptions(
            name='image_for_car_positioncategory',
            options={'verbose_name_plural': 'Image_for_Car_PositionCategories'},
        ),
    ]
