# Generated by Django 3.2.9 on 2021-11-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_appearance_detail_interior_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='car.positioncategory'),
        ),
    ]
