# Generated by Django 3.2.9 on 2021-11-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_position_position_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='car.positioncategory'),
        ),
    ]
