# Generated by Django 3.2.9 on 2021-11-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0010_alter_position_position_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('working_time', models.CharField(max_length=255)),
                ('location_length', models.DecimalField(decimal_places=5, max_digits=10)),
                ('location_width', models.DecimalField(decimal_places=5, max_digits=10)),
                ('position', models.ManyToManyField(related_name='dealers', to='car.Position')),
            ],
        ),
    ]
